In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
csv_file_path ='/Users/sameershekhar/Desktop/ML Live Class/Modular/ML-Live-Class/data/Advertising.csv'
df = pd.read_csv(csv_file_path, usecols = ['TV',	'Radio',	'Newspaper',	'Sales'])
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop(['Sales'], axis=1)
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [4]:
y = df['Sales']
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [14]:
from sklearn.preprocessing import PolynomialFeatures
poly_conv = PolynomialFeatures(degree = 3, include_bias = False)

In [15]:
from sklearn.linear_model import LinearRegression
final_model = LinearRegression()

In [16]:
poly_features = poly_conv.fit_transform(X)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size = 0.33, random_state = 101)


In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [19]:
scaler.fit(X_train)

StandardScaler()

In [20]:
scaled_X_train = scaler.transform(X_train)

In [21]:
scaler.fit(X_test)

StandardScaler()

In [22]:
scaled_X_test = scaler.transform(X_test)

In [23]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [24]:
scaled_X_train[0]

array([ 0.455913  , -0.15469995, -0.98899258,  0.23144458,  0.12990319,
       -0.57856073, -0.43655678, -0.66806654, -0.71668198,  0.02389419,
        0.04869878, -0.45436665, -0.22089285, -0.47664217, -0.51504813,
       -0.55818067, -0.60618091, -0.56426029, -0.5063835 ])